import type { Metadata } from 'next';
import { clsx } from 'clsx';
import { connectToMongoDB } from '@/lib/mongo';
import { Roboto } from 'next/font/google';
import { Footer, Header } from '@/widgets';
import { ThemeProvider } from 'next-themes';
import './globals.scss';
import styles from './layout.module.scss';

const roboto = Roboto({
  weight: ['400', '300', '700'],
  subsets: ['latin', 'cyrillic-ext'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectToMongoDB();
  return (
    <html lang="ru" suppressHydrationWarning>
      <ThemeProvider attribute="class">
        <body
          className={clsx(
            roboto.className,
            styles.body,
            styles.wrapper,
            'body'
          )}
          suppressHydrationWarning
        >
          <Header className={styles.header} />
          <main className={styles.main}>{children}</main>
          <Footer className={styles.footer} />
        </body>
      </ThemeProvider>
    </html>
  );
}
