import type { Metadata } from 'next';
import { clsx } from 'clsx';
import { connectToMongoDB } from '@/lib/mongo';
import { Roboto } from 'next/font/google';
import './globals.css';
import styles from './layout.module.scss';
import { SnipperListSkeleton, SnippetList } from '@/features';
import { Suspense } from 'react';

const roboto = Roboto({
  weight: ['400', '300', '700'],
  subsets: ['latin', 'cyrillic-ext'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectToMongoDB();
  return (
    <html lang="ru">
      <body className={clsx(roboto.className, styles.body, styles.wrapper)}>
        <header className={styles.header}></header>
        <aside className={styles.sidebar}>
          {/* {
            <Suspense fallback={<SnipperListSkeleton />}>
              <SnippetList />
            </Suspense>
          } */}
        </aside>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}></footer>
      </body>
    </html>
  );
}
